### ISSUE TITLE
gl cann't surpport chinese

### ISSUE THREAD

**Issue by PhoenixPtt** [tadmccorkle/markdown.nvim#11]
![image](https://github.com/tadmccorkle/markdown.nvim/assets/68508116/9f022b12-6926-4d1c-87b5-be00ee5a8fe4)
after type gl
![image](https://github.com/tadmccorkle/markdown.nvim/assets/68508116/775d8227-8f11-45b9-b78b-6d887e352602)

**Comment by tadmccorkle** [comment]
The current visual range implementation doesn't handle non-ascii characters. Visual surround with emphasis/bold/strikethrough also doesn't work for all characters. I'll look into fixing this.

**Comment by PhoenixPtt** [comment]
> @PhoenixPtt The current visual range implementation doesn't handle non-ascii characters. Visual surround with emphasis/bold/strikethrough also doesn't work for all characters. I'll look into fixing this.

thanks for your reply!
